""" Initialize Vundle
filetype off
set rtp+=~/.vim,~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

""" Color Theme

Plugin 'altercation/vim-colors-solarized'

""" Language Support

Plugin 'kchmck/vim-coffee-script'
Plugin 'chrisbra/csv.vim'
Plugin 'elixir-lang/vim-elixir'
Plugin 'jimenezrick/vimerl'
Plugin 'tpope/vim-haml'
Plugin 'nono/vim-handlebars'
Plugin 'digitaltoad/vim-jade'
Plugin 'pangloss/vim-javascript'
Plugin 'elzr/vim-json'
Plugin 'groenewege/vim-less'
Plugin 'tpope/vim-markdown'
Plugin 'mmalecki/vim-node.js'
Plugin 'vim-ruby/vim-ruby'
Plugin 'rosstimson/scala-vim-support'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'wavded/vim-stylus'
Plugin 'timcharper/textile.vim'

""" Tools

Plugin 'rking/ag.vim'
Plugin 'bling/vim-airline'
Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'tpope/vim-bundler'
Plugin 'ap/vim-css-color'
Plugin 'kien/ctrlp.vim'
Plugin 'rizzatti/dash.vim'
Plugin 'tpope/vim-dispatch'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-git'
Plugin 'mattn/gist-vim'
"Plugin 'airblade/vim-gitgutter'  " disabled because makes things slow
Plugin 'junegunn/goyo.vim'
Plugin 'sjl/gundo.vim'
Plugin 'michaeljsmith/vim-indent-object'
Plugin 'rgarver/Kwbd.vim'
Plugin 'edsono/vim-matchit'
Plugin 'chrisbra/NrrwRgn'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'reedes/vim-pencil'
Plugin 'dsawardekar/portkey'
Plugin 'tpope/vim-rbenv'
Plugin 'tpope/vim-repeat'
Plugin 'duff/vim-scratch'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/syntastic'
Plugin 'godlygeek/tabular'
Plugin 'majutsushi/tagbar'
Plugin 'kana/vim-textobj-user'
Plugin 'nelstrom/vim-textobj-rubyblock'
Plugin 'tomtom/tlib_vim'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'edkolev/tmuxline.vim'
Plugin 'SirVer/ultisnips'
Plugin 'tpope/vim-unimpaired'
Plugin 'benmills/vimux'
Plugin 'sjl/vitality.vim'
Plugin 'skalnik/vim-vroom'
Plugin 'mattn/webapi-vim'
Plugin 'vim-scripts/YankRing.vim'
if v:version >= 704 || v:version == 703 && has("patch584")
  Plugin 'Valloric/YouCompleteMe'
end
Plugin 'itspriddle/ZoomWin'
Plugin 't9md/vim-ruby-xmpfilter'
Plugin 'amix/vim-zenroom2'

""" Framework Support

Plugin 't9md/vim-chef'
Plugin 'tpope/vim-cucumber'
Plugin 'dsawardekar/ember.vim'
Plugin 'sunaku/vim-ruby-minitest'
Plugin 'ajf/puppet-vim'
Plugin 'tpope/vim-rails'
Plugin 'thoughtbot/vim-rspec'

""" Finalize Vundle

call vundle#end()
filetype plugin indent on

""" Color Theme

let g:solarized_menu = 0
let g:solarized_contrast = "high"
set background=light
if $USER == "action" " running in nitrous.io without proper colors
  let g:solarized_termcolors=256
end
color solarized
syntax enable

""" Settings

source ~/.vim/setup/settings.vim
source ~/.vim/setup/filetypes.vim
source ~/.vim/setup/mappings.vim
source ~/.vim/setup/plugin_settings.vim
source ~/.vim/setup/plugin_mappings.vim
