# ~/.tmuxinator/100s.yml
# you can make as many windows as you wish...

name: 🐦 100S 
root: ~/Code/100Starlings/100s-cli
startup_window: shell
windows:
  - :
      layout: main-horizontal
      panes:
        - vim
  - : lazygit
  - shell: git pull
  - ledger:
      root: ~/Code/100Starlings/100s-cli/ledger
  - invoices:
      layout: even-horizontal
      env:
        ASDF_RUBY_VERSION: 2.7.7
      panes:
        - root: cd "$FINANCE_PATH/Invoices Received"
        - root: cd "$FINANCE_PATH/Invoices Paid"
