# ~/.tmuxinator/100starlings.yml
# you can make as many windows as you wish...

project_name: 100Starlings
project_root: ~/Code/100Starlings/100starlings
windows:
  - editor: vim
  - shell:
  - server: yarn next dev
