# ~/.tmuxinator/elixir.yml
# you can make as many tabs as you wish...

name: Elixir 
root: ~/Code/elixir-lang/elixir
windows:
  - editor: vim
  - iex:
      layout: even-vertical
      panes:
        - iex --sname apple -S mix
        - iex --sname banana -S mix
  - shell:
