<%
path, name = @args
name ||= path.split("/").last
%>

name: "<%= name %> "
root: ~/Code/<%= path %>
startup_window: shell
windows:
  - :
      layout: main-horizontal
      panes:
        - vim
  - : lazygit
  - shell: git pull
  - : bin/rails console
