# ~/.tmuxinator/redshift_ecto.yml
# you can make as many tabs as you wish...

name: RedshiftEcto 
root: ~/Code/100Starlings/redshift_ecto
startup_window: shell
windows:
  - : vim
  - :
      layout: even-vertical
      panes:
        - iex -S mix
  - shell: git pull
  - ecto:
      index: 8
      root: ~/Code/elixir-ecto/ecto
      layout: even-vertical
      panes:
        - vim
  - ecto_sql:
      index: 9
      root: ~/Code/elixir-ecto/ecto_sql
      layout: even-vertical
      panes:
        - vim
