#!/bin/sh

if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi
vim +BundleInstall +qa

for rcfile in $(ls ~/.zprezto/runcoms/*); do
  filename="$(basename $rcfile)"
  dotfile="$HOME/.$filename"
  [ "$filename" = "README.md" -o -L "$dotfile" ] && continue

  if [ -f "$dotfile" ]; then
    rm -i "$dotfile"
  fi

  ln -s "$rcfile" "$dotfile"
done
