#!/usr/bin/env bash

# setup prezto for configuring ZSH
git clone --recurse-submodules https://github.com/sorin-ionescu/prezto.git $HOME/.zprezto
cd $HOME/.zprezto/modules/prompt/external/pure
git checkout main

# setup Mac OS related dotfiles
rcup -t osx

# enable key remapping
launchctl load $HOME/Library/LaunchAgents/remap-keys.plist

# reconfigure Mac OS settings
$HOME/.macos

# install asdf and various languages
git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf
. $HOME/.asdf/asdf.sh

asdf plugin add ruby
asdf install ruby latest
asdf install ruby 2.7.4
asdf global ruby 2.7.4

asdf plugin add erlang
asdf install erlang latest
asdf global erlang latest

asdf plugin add elixir
asdf install elixir latest
asdf global elixir latest

asdf plugin add nodejs
asdf install nodejs latest
asdf global nodejs latest

asdf plugin add rust
asdf install rust stable
asdf global rust stable

# install LunarVim and restore our config
mkdir -p $HOME/Code/LunarVim
git clone https://github.com/LunarVim/LunarVim $HOME/Code/LunarVim/LunarVim
$HOME/Code/LunarVim/LunarVim/utils/installer/install.sh --local --install-dependencies
rm -rf $HOME/.config/lvim $HOME/.config/lvim.bak
rcup -t vim
