#!/usr/bin/env bash

# setup prezto for configuring ZSH
git clone --recurse-submodules https://github.com/sorin-ionescu/prezto.git $HOME/.zprezto

# setup Mac OS related dotfiles
rcup -t osx

# reconfigure Mac OS settings
$HOME/.macos

# install asdf and various languages
git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf
. $HOME/.asdf/asdf.sh

asdf plugin add ruby
asdf install ruby latest
asdf install ruby 2.7.4
asdf global ruby 2.7.4

asdf plugin add erlang
asdf install erlang latest
asdf global erlang latest

asdf plugin add elixir
asdf install elixir latest
asdf global elixir latest

asdf plugin add nodejs
asdf install nodejs latest
asdf global nodejs latest

asdf plugin add rust
asdf install rust stable
asdf global rust stable

# setup TPM
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# install gems for Pry
gem install -N -i ~/.prygems pry pry-doc pry-remote pry-stack_explorer awesome_print coderay hirb

# change some application configuration
defaults write org.hammerspoon.Hammerspoon MJConfigFile "~/.config/hammerspoon/init.lua"
